name       : openfx-arena
version    : 2.3.14
release    : 21
source     :
    - git|https://github.com/NatronGitHub/openfx-arena.git : Natron-2.3.14
license    : GPL-2.0-only
component  : multimedia.graphics
networking : yes
summary    : A set of OpenFX visual effect plugins
description: |
    A set of OpenFX visual effect plugins
builddeps  :
    - pkgconfig(IlmBase)
    - pkgconfig(libcdr-0.1)
    - pkgconfig(libheif)
    - pkgconfig(libjpeg)
    - pkgconfig(libopenjp2)
    - pkgconfig(libraw_r)
    - pkgconfig(librevenge-0.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(libzip)
    - pkgconfig(Magick++)
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - pkgconfig(poppler)
    - bzip2-devel
build      : |
    %make CONFIG=release IM=7
install    : |
    %make_install \
        PLUGINPATH=/usr/share/OFX/Plugins \
        CONFIG=release \
        IM=7
