name       : openfx-arena
version    : 2.1.9
release    : 2
source     :
    - https://github.com/MrKepzie/Natron/releases/download/2.1.9/openfx-arena-2.1.9.tar.xz : 6ee279e5975ff2ba760f579674e02cf9ea7f84bee1536c4f57aee164f7086a61
license    : BSD-3-Clause
component  : multimedia.graphics
summary    : A set of OpenFX visual effect plugins
description: |
    A set of OpenFX visual effect plugins
networking : yes
builddeps  :
    - pkgconfig(autotrace)
    - pkgconfig(IlmBase)
    - pkgconfig(libcdr-0.1)
    - pkgconfig(libjpeg)
    - pkgconfig(librevenge-0.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(libzip)
    - pkgconfig(Magick++)
    - pkgconfig(OpenColorIO)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - pkgconfig(poppler)
build      : |
    %make CONFIG=release IM=7
install    : |
    %make_install \
        PLUGINPATH=/usr/share/OFX/Plugins \
        CONFIG=release \
        IM=7
